# Generated by Django 4.0.4 on 2022-05-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('1', 'First'), ('2', 'Second')], max_length=1)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
