# Generated by Django 4.0.4 on 2022-06-15 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'My Subjects'},
        ),
    ]
