# Generated by Django 4.0.4 on 2022-05-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_options_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
