# Generated by Django 4.0.4 on 2022-06-15 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'My Users'},
        ),
    ]
