# Generated by Django 4.0.4 on 2022-06-15 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_date_create_alter_class_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name_plural': 'My Classes'},
        ),
    ]
